Product.create!([
  {name: "oranges", price: "3.0", image_url: "https://i.pinimg.com/736x/05/79/5a/05795a16b647118ffb6629390e995adb.jpg", description: "a fruit named for how it tastes", in_stock: nil},
  {name: "rice", price: "50.0", image_url: "https://static01.nyt.com/images/2018/02/21/dining/00RICEGUIDE8/00RICEGUIDE8-articleLarge.jpg", description: "70lb bag. Good for when you want to eat 1000 of something", in_stock: nil},
  {name: "lemonade", price: "1.0", image_url: "https://www.simplyrecipes.com/wp-content/uploads/2006/06/lemonade-vertical-2-dm.jpg", description: "looks like gasoline but tastes a little better", in_stock: nil},
  {name: "bread", price: "5.0", image_url: "https://i2.wp.com/butterwithasideofbread.com/wp-content/uploads/2019/07/White-Bread_10.bsb_.jpg?ssl=1", description: "not that nasty whole grain stuff", in_stock: nil},
  {name: "eggs", price: "2.0", image_url: "https://x9wsr1khhgk5pxnq1f1r8kye-wpengine.netdna-ssl.com/wp-content/uploads/how-long-do-eggs-last-930x550-1-930x550.jpg", description: "un-scrambled", in_stock: nil},
  {name: "sugar", price: "5.0", image_url: "https://images.theconversation.com/files/307440/original/file-20191217-58292-nlmvmh.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=926&fit=clip", description: "it tastes pretty good", in_stock: nil},
  {name: "gasoline", price: "2.0", image_url: "https://www.fuelfreedom.org/wp-content/uploads/gasoline2.png", description: "Gasoline is a petroleum-derived liquid mixture consisting primarily of hydrocarbons, used as fuel in internal combustion engines.\n\nBefore internal combustion engines were invented in the mid-1800s, gasoline was sold in small bottles as a treatment against lice and their eggs.\n\nThis treatment method is no longer common because of the inherent fire hazard and the risk of dermatitis.\n\nGasoline is produced in oil refineries.\n\nMaterial that is separated from crude oil via distillation, called natural gasoline, does not meet the required specifications for modern engines, but will form part of the blend.\n\nThe bulk of a typical gasoline consists of hydrocarbons with between 5 and 12 carbon atoms per molecule.\n\nMany of these hydrocarbons are considered hazardous substances and, in the United States, are regulated by the Occupational Safety and Health Administration.", in_stock: nil}
])
